server:
  port: 80
spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:9999  #监控
#  sleuth:
#    sampler:
#      percentage: 1  #监测比例，默认为0.1，设置为1则为每次http动作都监控，但是对性能会有影响
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
  instance:
    prefer-ip-address:true



zuul:
  routes:
    service-user:
      path: /service-user/**
      serviceId: service-user
    service-messenger:
          path: /messenger/**
          serviceId: messenger


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
